language: node_js
node_js:
  - "8"
script: "npm run test:coverage"


after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

before_deploy:
  - cd dox
  - npm install
  - npm run build
  - cd ..
  - cp -R docx/dist .site
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: .site
  on:
    branch: master
