language: node_js

node_js:
  - "8"


script: yarn run test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --frozen-lockfile



after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache:
  yarn: true
  directories:
    - node_modules
